version: "3.9"

name: library

services:
  # -----------------------
  # MS SQL Server
  # -----------------------
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Your_password123", "-C", "-Q", "SELECT 1"]
      interval: 10s
      retries: 10
      start_period: 20s

  # -----------------------
  # Liquibase runner
  # -----------------------
  liquibase:
    image: liquibase/liquibase
    container_name: liquibase
    depends_on:
      mssql:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    working_dir: /migrations
    command:
      - --url=jdbc:sqlserver://mssql:1433;encrypt=true;trustServerCertificate=true
      - --username=sa
      - --password=Your_password123
      - --changeLogFile=db.changelog-master.yaml
      - update

  # -----------------------
  # ElasticSearch
  # -----------------------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"'"]
      interval: 10s
      retries: 10

  # -----------------------
  # Redis
  # -----------------------
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # -----------------------
  # .NET API
  # -----------------------
  api:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: myapi
    build:
      context: .
      dockerfile: ./Library/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - mssql
      - elasticsearch
      - redis
      - liquibase
    environment:
      ConnectionStrings__DefaultConnection: "Server=mssql,1433;Database=master;User Id=sa;Password=Your_password123;encrypt=true;trustServerCertificate=true"
      Elastic__Url: "http://elasticsearch:9200"
      Redis__ConnectionString: "redis:6379"

volumes:
  redis-data:
  mssql-data: